name: sde
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - pip=22.2.2
  - pytorch-cuda=11.8
  - pytorch=2.0.1
  - pandas=2.1.1
  - scikit-learn=1.3.2
  - pip:
    - tensorboard==2.12.3
    - tqdm>=4.62.3
    - pillow==9.5.0
    - notebook==6.4.5
    - jupyterlab>=3.6.3
    - matplotlib==3.7.1
    - seaborn==0.12.2
    - ipywidgets==7.6.5
    - pyro-ppl==1.8.4